import pandas as pd
gu = pd.read_csv("C:/teamwork/SeoulEVCheck/data/gu_day.csv", encoding="utf-8-sig")
st = pd.read_csv("C:/teamwork/SeoulEVCheck/data/station_day.csv", encoding="utf-8-sig")
print("=== gu_day ===")
print("rows:", len(gu), "  cols:", len(gu.columns))
print("columns:", list(gu.columns))
print("missing:", gu.isnull().sum().sum())
print("duplicates:", gu.duplicated().sum())
print("numeric:", len(gu.select_dtypes(include="number").columns))
print("object:", len(gu.select_dtypes(include="object").columns))
print()
print("=== station_day ===")
print("rows:", len(st), "  cols:", len(st.columns))
print("columns:", list(st.columns))
print("missing:", st.isnull().sum().sum())
print("duplicates:", st.duplicated().sum())
print("numeric:", len(st.select_dtypes(include="number").columns))
print("object:", len(st.select_dtypes(include="object").columns))
